public enum Token {
    PALABRA_RESERVADA, PUNTO_COMA, IDENTIFICADOR,
    PARENTESIS_CIERRE, PARENTESIS_APERTURA, LLAVE_APERTURA,
    LLAVE_CIERRE, NUMERO, MAYOR_QUE, MENOR_QUE, SUMA, RESTA,
    COMPARADOR_IGUAL, SIGNO_IGUAL, ERROR, CLASS, IF, INT, BOOLEAN,
    WHILE, TRUE, FALSE, READ, PRINT; 
}
